## Model 2

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
# import numerical data
data_num = pd.read_csv('data/AmesHousingNumData.csv')
data_num = data_num.drop('Unnamed: 0', axis=1) 
data_num.head()

,Mas Vnr Area,Garage Yr Blt,Year Remod/Add,Full Bath,Year Built,1st Flr SF,Total Bsmt SF,Garage Area,Garage Cars,Gr Liv Area,Overall Qual,SalePrice
0,0.055607,-0.730498,-1.155886,-1.019607,-0.368243,1.281557,0.065626,0.258714,0.309465,0.313663,-0.061812,5.332438
1,-0.569515,-0.689605,-1.107938,-1.019607,-0.335146,-0.675537,-0.384244,1.197200,-1.003952,-1.192617,-0.771063,5.021189
2,0.033281,-0.812285,-1.251781,-1.019607,-0.434438,0.439492,0.631372,-0.744814,-1.003952,-0.334434,-0.061812,5.235528
3,-0.569515,-0.403350,-0.772303,0.794069,-0.103465,2.450663,2.405858,0.230839,0.309465,1.213467,0.647439,5.387390
4,-0.569515,0.782561,0.666134,0.794069,0.856357,-0.593133,-0.279728,0.045000,0.309465,0.260151,-0.771063,5.278525

In [3]:
# split nummerical data in input and target
target_num = data_num['SalePrice']
final_data_num = data_num.drop('SalePrice', axis=1)

# select the 2 most correlated features
final_data_numSelect = data_num[['Gr Liv Area', 'Overall Qual']]

display(final_data_numSelect.head())
display(final_data_num.head())

   Gr Liv Area  Overall Qual
0     0.313663     -0.061812
1    -1.192617     -0.771063
2    -0.334434     -0.061812
3     1.213467      0.647439
4     0.260151     -0.771063

,Mas Vnr Area,Garage Yr Blt,Year Remod/Add,Full Bath,Year Built,1st Flr SF,Total Bsmt SF,Garage Area,Garage Cars,Gr Liv Area,Overall Qual
0,0.055607,-0.730498,-1.155886,-1.019607,-0.368243,1.281557,0.065626,0.258714,0.309465,0.313663,-0.061812
1,-0.569515,-0.689605,-1.107938,-1.019607,-0.335146,-0.675537,-0.384244,1.197200,-1.003952,-1.192617,-0.771063
2,0.033281,-0.812285,-1.251781,-1.019607,-0.434438,0.439492,0.631372,-0.744814,-1.003952,-0.334434,-0.061812
3,-0.569515,-0.403350,-0.772303,0.794069,-0.103465,2.450663,2.405858,0.230839,0.309465,1.213467,0.647439
4,-0.569515,0.782561,0.666134,0.794069,0.856357,-0.593133,-0.279728,0.045000,0.309465,0.260151,-0.771063

In [4]:
# import categorical data
data_cat = pd.read_csv('data/AmesHousingCatData.csv')
data_cat = data_cat.drop('Unnamed: 0', axis=1) 

# select the input and target from categorical data
target_cat = data_cat['SalePrice']
final_data_cat = data_cat.drop('SalePrice', axis=1)
display(final_data_cat.head())

,MS Zoning_C (all),MS Zoning_FV,MS Zoning_I (all),MS Zoning_RH,MS Zoning_RL,MS Zoning_RM,Neighborhood_Blueste,Neighborhood_BrDale,Neighborhood_BrkSide,Neighborhood_ClearCr,...,Kitchen Qual_Po,Kitchen Qual_TA,Garage Finish_None,Garage Finish_RFn,Garage Finish_Unf,Garage Qual_Fa,Garage Qual_Gd,Garage Qual_None,Garage Qual_Po,Garage Qual_TA
0,0,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
1,0,0,0,1,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,1
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
3,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1

In [5]:
# import all data
data_all = pd.read_csv('data/AmesHousingPreprocessed.csv')
data_all = data_all.drop('Unnamed: 0', axis=1) 

# split data into input and target
target_all = data_all['SalePrice']
final_data_all = data_all.drop(['SalePrice', 'SalePrice.1'], axis=1)
display(final_data_all.head())

,MS Zoning_C (all),MS Zoning_FV,MS Zoning_I (all),MS Zoning_RH,MS Zoning_RL,MS Zoning_RM,Neighborhood_Blueste,Neighborhood_BrDale,Neighborhood_BrkSide,Neighborhood_ClearCr,...,Garage Yr Blt,Year Remod/Add,Full Bath,Year Built,1st Flr SF,Total Bsmt SF,Garage Area,Garage Cars,Gr Liv Area,Overall Qual
0,0,0,0,0,1,0,0,0,0,0,...,-0.730498,-1.155886,-1.019607,-0.368243,1.281557,0.065626,0.258714,0.309465,0.313663,-0.061812
1,0,0,0,1,0,0,0,0,0,0,...,-0.689605,-1.107938,-1.019607,-0.335146,-0.675537,-0.384244,1.197200,-1.003952,-1.192617,-0.771063
2,0,0,0,0,1,0,0,0,0,0,...,-0.812285,-1.251781,-1.019607,-0.434438,0.439492,0.631372,-0.744814,-1.003952,-0.334434,-0.061812
3,0,0,0,0,1,0,0,0,0,0,...,-0.403350,-0.772303,0.794069,-0.103465,2.450663,2.405858,0.230839,0.309465,1.213467,0.647439
4,0,0,0,0,1,0,0,0,0,0,...,0.782561,0.666134,0.794069,0.856357,-0.593133,-0.279728,0.045000,0.309465,0.260151,-0.771063

In [6]:
def preprocess(df, target, train_size = 0.7):
    
    """convert the pandas dataframes to numpy ndarrays"""
    
    X_np = df.to_numpy()
    y_np = target.to_numpy()
    
    # split the data into 70% training and 30% testing
    X_train, X_test, y_train, y_test = train_test_split(X_np, y_np, train_size=train_size, random_state=1265599650)
    
    return X_train, X_test, y_train, y_test

### Setting up the model

#### Version 1: Multivariate Linear Model

In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error


def calc_rmse(X_train, X_test, y_train, y_test, linear_model):
    
    linear_model.fit(X_train, y_train)
    
    predict = linear_model.predict(X_test)

    linear_test_rmse = np.sqrt(mean_squared_error(y_test, predict))
    
    print(f'The test RMSE for our multivariate linear model is {linear_test_rmse}')

    #print(f"The theta values for our multivariate linear model are:\n{linear_model.intercept_} and {linear_model.coef_}.")

#### Multivariate Polynomial Regression Model

Create new features from the existing ones. Check whether they add predictive value. 

1. Interaction Features

= Generate a new feature from the product of two features. Represents the interaction effect between two variables on dependent variable. 


2. Polynomial Feature Expansion

= Generate new features from the nth degree of each feature. 

Note: The second includes the first. The first is implemented to check whether including the interaction features alone improves the model or not. The second is implement to check whether features may have a non-linear relationship with the target feature.

Taken from http://www.eamonfleming.com/projects/housing-regression.html

#### Version 2: Interaction Features only

In [8]:
from sklearn.preprocessing import PolynomialFeatures

In [9]:
def poly_interact(X_train, X_test, y_train, y_test, poly_model_interact):

    # change feature matrix into polynomial feature matrix including interaction terms only
    poly_interact = PolynomialFeatures(interaction_only=True)
    X_train_interact = poly_interact.fit_transform(X_train)
    X_test_interact = poly_interact.fit_transform(X_test)
    
    poly_model_interact.fit(X_train_interact, y_train)

    predictions = poly_model_interact.predict(X_test_interact)

    poly_test_rmse = np.sqrt(mean_squared_error(y_test, predictions))

    print(f'The test RMSE for our interaction only polynomial model is {poly_test_rmse}')

    #print(f'The theta values for the interact linear model are:\n{poly_model_interact.coef_} and {poly_model_interact.intercept_}')

#### Version 3:  All Polynomial Features

In [10]:

def add_poly(X_train, X_test, y_train, y_test, poly_model, deg = 2):
    
    # change feature matrix into polynomial feature matrix
    poly = PolynomialFeatures(degree = deg)
    X_train_ = poly.fit_transform(X_train)
    X_test_ = poly.fit_transform(X_test)

    poly_model.fit(X_train_, y_train)

    predictions = poly_model.predict(X_test_)

    poly_test_rmse = np.sqrt(mean_squared_error(y_test, predictions))

    print(f'The test RMSE for our polynomial model is {poly_test_rmse}')

    #print(f'The theta values for our polynomial linear model are:\n{poly_model.coef_} and {poly_model.intercept_}')

### Testing and comparing the versions

In [11]:
X_train, X_test, y_train, y_test = preprocess(final_data_numSelect, target_num, train_size =0.7)

In [12]:
print(f'These are the outcomes for just a selection of the numerical data:\n')

linear_model_numSelect = LinearRegression()
calc_rmse(X_train, X_test, y_train, y_test, linear_model_numSelect)

poly_model_interact_numSelect = LinearRegression()
poly_interact(X_train, X_test, y_train, y_test, poly_model_interact_numSelect)

poly_model_numSelect = LinearRegression()
add_poly(X_train, X_test, y_train, y_test, poly_model_numSelect, deg = 4)

print(f'\nDegree of 4 turned out to be the best degree if only 2 features are selected')

These are the outcomes for just a selection of the numerical data:

The test RMSE for our multivariate linear model is 0.08980180520039575
The test RMSE for our interaction only polynomial model is 0.08956889397883937
The test RMSE for our polynomial model is 0.08475612213616365

Degree of 4 turned out to be the best degree if only 2 features are selected

In [13]:
X_train, X_test, y_train, y_test = preprocess(final_data_num, target_num, train_size =0.7)

In [14]:
print(f'These are the outcomes for all the numerical data:\n')
linear_model_num = LinearRegression()
calc_rmse(X_train, X_test, y_train, y_test, linear_model_num)

poly_model_interact_num = LinearRegression()
poly_interact(X_train, X_test, y_train, y_test, poly_model_interact_num)

poly_model_num = LinearRegression()
add_poly(X_train, X_test, y_train, y_test, poly_model_num, deg = 2)

print(f'\nDegree of 2 was found to be the best fit')

These are the outcomes for all the numerical data:

The test RMSE for our multivariate linear model is 0.07730015854623123
The test RMSE for our interaction only polynomial model is 0.06973284142381102
The test RMSE for our polynomial model is 0.06867811274933439

Degree of 2 was found to be the best fit

In [15]:
print(f'These are the outcomes for all the categorical data:\n')

X_train, X_test, y_train, y_test = preprocess(final_data_cat, target_cat, train_size =0.7)

linear_model_cat = LinearRegression()
calc_rmse(X_train, X_test, y_train, y_test, linear_model_cat)

poly_model_interact_cat = LinearRegression()
poly_interact(X_train, X_test, y_train, y_test, poly_model_interact_cat)

poly_model_cat = LinearRegression()
add_poly(X_train, X_test, y_train, y_test, poly_model_cat)

These are the outcomes for all the categorical data:

The test RMSE for our multivariate linear model is 0.09439593925447883
The test RMSE for our interaction only polynomial model is 51208698421.750244
The test RMSE for our polynomial model is 28431325497.24416

In [16]:
print(f'These are the outcomes for all the combined data\n')
X_train, X_test, y_train, y_test = preprocess(final_data_all, target_all, train_size =0.7)

linear_model_all = LinearRegression()
calc_rmse(X_train, X_test, y_train, y_test, linear_model_all)

poly_model_interact_all = LinearRegression()
poly_interact(X_train, X_test, y_train, y_test, poly_model_interact_all)

poly_model_all = LinearRegression()
add_poly(X_train, X_test, y_train, y_test, poly_model_all)

These are the outcomes for all the combined data

The test RMSE for our multivariate linear model is 21485781718.839066
The test RMSE for our interaction only polynomial model is 729643151.883984
The test RMSE for our polynomial model is 1112138415.5519755

#### Optional: Evaluate Feature Importance

In [17]:
poly = PolynomialFeatures(degree=2)

# only implement for all combined data
X_train_ = poly.fit_transform(X_train)

# add appropriate names to polynomial features
X_train_ = pd.DataFrame(X_train_, columns = poly.get_feature_names(final_data_all.columns))

# generate list of polynomial features and their correlations with sale price
X_train_correlations = X_train_.corrwith(target_all)

# sort features from highest positively correlated with sale price
print('The highest positively correlated features with sale price are:')
X_train_correlations.sort_values(ascending = False).head(20)

The highest positively correlated features with sale price are:

Neighborhood_ClearCr Garage Qual_Gd          0.070615
MS Zoning_FV Mas Vnr Type_BrkFace            0.070311
MS Zoning_RH Overall Qual                    0.065112
Neighborhood_NridgHt Garage Finish_RFn       0.057233
Neighborhood_NPkVill Exter Qual_Gd           0.057145
Mas Vnr Type_Stone Garage Finish_RFn         0.056122
Neighborhood_SawyerW Overall Qual            0.055587
Neighborhood_Sawyer 1st Flr SF               0.053800
Neighborhood_Somerst Mas Vnr Type_BrkFace    0.052764
MS Zoning_RH Mas Vnr Area                    0.051873
Bsmt Qual_TA Gr Liv Area                     0.051352
Neighborhood_SawyerW Year Remod/Add          0.051188
Neighborhood_NridgHt Kitchen Qual_Gd         0.051145
Neighborhood_NridgHt Bsmt Qual_Gd            0.048886
Neighborhood_Gilbert Exter Qual_TA           0.048060
Neighborhood_BrkSide Garage Area             0.046388
Bsmt Qual_None Kitchen Qual_Gd               0.046340
Neighborhood_BrkSide Garage Cars             0.046212
Exter Qual_Gd Bsmt Qual_None                 0.045561
Neighborhood_Somerst Mas Vnr Area            0.045428
dtype: float64

In [18]:
# sort features from highest negatively correlated with sale price
print('The highest negatively correlated features with sale price are:')
X_train_correlations.sort_values().head(20)

The highest negatively correlated features with sale price are:

Kitchen Qual_Gd Garage Qual_Fa            -0.085675
Neighborhood_BrkSide Garage Qual_None     -0.080548
Neighborhood_BrkSide Garage Finish_None   -0.080548
MS Zoning_RH Neighborhood_SawyerW         -0.059268
MS Zoning_RH Bsmt Qual_TA                 -0.058901
MS Zoning_RH Central Air_Y                -0.058434
Neighborhood_Greens 1st Flr SF            -0.057995
Neighborhood_MeadowV Kitchen Qual_Gd      -0.056255
Garage Area Overall Qual                  -0.054104
Neighborhood_BrkSide Kitchen Qual_Fa      -0.053242
MS Zoning_RL Neighborhood_BrkSide         -0.053180
Garage Cars Overall Qual                  -0.052576
Neighborhood_SawyerW Exter Qual_Fa        -0.052259
MS Zoning_RH Exter Qual_Fa                -0.052259
Neighborhood_BrkSide Exter Qual_Gd        -0.051688
MS Zoning_RH Garage Finish_Unf            -0.051549
Kitchen Qual_Fa Garage Qual_None          -0.048934
Kitchen Qual_Fa Garage Finish_None        -0.048934
MS Zoning_RH Mas Vnr Type_None            -0.047653
Year Remod/Add Gr Liv Area                -0.047499
dtype: float64